# Generated by Django 3.2.3 on 2021-05-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdevice',
            old_name='deviceName',
            new_name='deviceHostname',
        ),
    ]
