# Generated by Django 3.2.4 on 2021-06-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210604_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='deviceMagX',
            field=models.FloatField(default=69.69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='deviceMagY',
            field=models.FloatField(default=88.88),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='deviceMagZ',
            field=models.FloatField(default=789.789),
            preserve_default=False,
        ),
    ]
